Add temporary nagios check support to lets us know when we move off the LE X3 intermediate.  cf tpo/tpa/team#40052

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -25,18 +25,24 @@ deploy_cert() {
   chain="$b/chain.pem"
   chained="$b/fullchain.pem"
 
-  mkdir -p "$RES"
-  install -m 0600 "$key" "$RES/$name.key"
-  install -m 0644 "$cert" "$RES/$name.crt"
-  install -m 0644 "$chain" "$RES/$name.crt-chain"
-  install -m 0644 "$chained" "$RES/$name.crt-chained"
+  if openssl x509 -text < "$chain" | grep "Let's Encrypt Authority X3"; then
+    mkdir -p "$RES"
+    install -m 0600 "$key" "$RES/$name.key"
+    install -m 0644 "$cert" "$RES/$name.crt"
+    install -m 0644 "$chain" "$RES/$name.crt-chain"
+    install -m 0644 "$chained" "$RES/$name.crt-chained"
 
-  size=$(openssl rsa  < "$key" -text -noout | awk -F: '$1 == "Private-Key" {print $2}' | sed -e 's/[^0-9]//g')
-  e="$BASE/var/extra/dh-$size.pem"
-  if [ -e "$e" ]; then
-    cat "$e" >> "$RES/$name.crt-chained"
+    size=$(openssl rsa  < "$key" -text -noout | awk -F: '$1 ~ /Private-Key/ {print $2}' | sed -e 's/ bit.*//; s/[^0-9]//g')
+    e="$BASE/var/extra/dh-$size.pem"
+    if [ -e "$e" ]; then
+      cat "$e" >> "$RES/$name.crt-chained"
+    else
+      echo >&2 "Warning: No $e file found."
+    fi
   else
-    echo >&2 "Warning: No $e file found."
+    echo 2>&2 "Invalid chain! cf.  tpo/tpa/team#40052"
+    touch /home/letsencrypt/non-X3-cert-encountered
+    exit 1
   fi
 }
 
